apiVersion: v1
kind: Service
metadata:
  name: {{ include "town.name" . }}
  namespace: {{ include "town.namespace" . }}
  labels:
    {{- include "town.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "town.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
